Обработаны исключения #1
onlyholy1337/area_test pull request #2
Opened 2024-06-11 13:06 UTC by onlyholy1337

Исправлены синтактические ошибки
Обработаны исключения

2024-06-11 13:15 UTC, Ayssmi0 requested changes
Кто-то делает ошибки, ай-яй-яй

2024-06-11 17:19 UTC, onlyholy1337 commented
А сейчас? @Ayssmi0 посмотри пожалуйста

2024-06-12 09:33 UTC, onlyholy1337 commented
А сейчас? @WantToSleep1337 проверь пожалуйста

2024-06-12 09:36 UTC, WantToSleep1337 commented
Все ок. Можно мержить.

2024-06-12 09:36 UTC, WantToSleep1337 approved these changes
Все ок. Можно мержить.

2024-06-12 09:37 UTC, merged

2024-06-13 03:42 UTC, Ayssmi0 reviewed
Все хорошо, отличный проект